# Datasource configuration in heroku environment
server:
  context-path: /regactapi
  port: 8080
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      
  datasource:  
    url: jdbc:postgresql://localhost:5432/regact-api
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres